[package]
name = "pytalos"
version = "0.1.0"
edition.workspace = true

[lib]
name = "pytalos"
crate-type = ["cdylib"]

[dependencies]
talos_core = { path = "../talos-core" }
talos_model = { path = "../talos-model" }
talos_ls = { path = "../talos-ls" }
itertools = "0.14.0"
pyo3 = { version = "0.28.2", features = ["abi3-py38"] }
